In [1]:
!pip install numpy

In [1]:
import numpy as np

In [5]:
lst=[1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [6]:
arr=np.array(lst)

In [7]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
[i**2 for i in lst]

[1, 4, 9, 16, 25]

In [8]:
%timeit [i**2 for i in lst]

822 ns ± 10.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
arr**2

array([ 1,  4,  9, 16, 25])

In [10]:
%timeit arr**2

976 ns ± 53.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
# creating numpy\n_d arrays

In [2]:
import numpy as np

In [3]:
arr1=np.array([1,2,3,4,5])

In [4]:
arr1

array([1, 2, 3, 4, 5])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
type(arr2)

numpy.ndarray

In [9]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
arr4=np.ones((3,3))
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
arr5=np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
type(arr5)

numpy.ndarray

In [14]:
arr6=np.arange(10)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
type(arr6)

numpy.ndarray

In [16]:
arr6=np.arange(5,16)
arr6

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [17]:
arr6=np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [18]:
arr7=np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [19]:
arr8=arr7.copy()
arr8

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

# properties and attributes

In [20]:
arr1

array([1, 2, 3, 4, 5])

In [21]:
arr1.shape

(5,)

In [22]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
arr2.shape

(2, 3)

In [24]:
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
arr3.shape

(2, 3)

In [26]:
arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
arr4.shape

(3, 3)

In [28]:
arr9=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
arr9.shape

(2, 2, 2)

In [30]:
arr9.ndim

3

In [31]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr2.ndim

2

In [33]:
arr1

array([1, 2, 3, 4, 5])

In [34]:
arr1.ndim

1

In [35]:
arr1.size # no of items in list is the size value

5

In [36]:
arr9.size

8

In [37]:
arr9.itemsize

4

In [39]:
arr8.itemsize

8

In [40]:
arr8.dtype

dtype('float64')

In [41]:
arr9.dtype

dtype('int32')

In [42]:
arr9.astype('float') # astype coverts into float and integer  values

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

In [45]:
arr7.astype('int') 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 20])